/*
 * Copyright (c) 2026, PenNameLuXun
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef PLATFORM_DEF_H
#define PLATFORM_DEF_H

#include <arch.h>
#include <lib/utils_def.h>
#include <plat/common/common_def.h>

#define PLATFORM_STACK_SIZE		0x1000

#define PLATFORM_CPU_PER_CLUSTER_SHIFT	U(2)
#define PLATFORM_MAX_CPUS_PER_CLUSTER	(U(1) << PLATFORM_CPU_PER_CLUSTER_SHIFT)
#define PLATFORM_CLUSTER_COUNT		U(1)
#define PLATFORM_CLUSTER0_CORE_COUNT	U(4)
#define PLATFORM_CLUSTER1_CORE_COUNT	U(0)
#define PLATFORM_CORE_COUNT		PLATFORM_CLUSTER0_CORE_COUNT
#define QEMU_PRIMARY_CPU		U(0)

#define PLAT_NUM_PWR_DOMAINS		(PLATFORM_CLUSTER_COUNT + \
					 PLATFORM_CORE_COUNT)
#define PLAT_MAX_PWR_LVL		MPIDR_AFFLVL1

#define PLAT_MAX_RET_STATE		U(1)
#define PLAT_MAX_OFF_STATE		U(2)

#define PLAT_LOCAL_STATE_RUN		U(0)
#define PLAT_LOCAL_STATE_RET		U(1)
#define PLAT_LOCAL_STATE_OFF		U(2)

#define PLAT_LOCAL_PSTATE_WIDTH		4
#define PLAT_LOCAL_PSTATE_MASK		((1 << PLAT_LOCAL_PSTATE_WIDTH) - 1)

#define CACHE_WRITEBACK_SHIFT		6
#define CACHE_WRITEBACK_GRANULE		(1 << CACHE_WRITEBACK_SHIFT)

/*
 * Keep the top 16 MiB of DRAM out of the non-secure view so BL31 runtime
 * text/stack state stays intact after U-Boot relocates and later boots BL33.
 */
#define NS_DRAM0_BASE			ULL(0x40000000)
#define NS_DRAM0_SIZE			ULL(0x7f000000)

#define SEC_SRAM_BASE			0xbf000000
#define SEC_SRAM_SIZE			0x01000000
#define SEC_DRAM_BASE			SEC_SRAM_BASE
#define SEC_DRAM_SIZE			0

#define SHARED_RAM_BASE			SEC_SRAM_BASE
#define SHARED_RAM_SIZE			0x00001000

#define PLAT_QEMU_HOLD_BASE		SHARED_RAM_BASE
#define PLAT_QEMU_HOLD_SIZE		(PLATFORM_CORE_COUNT * HOLD_SLOT_SIZE)

#define BL_RAM_BASE			(SHARED_RAM_BASE + SHARED_RAM_SIZE)
#define BL_RAM_SIZE			(SEC_SRAM_SIZE - SHARED_RAM_SIZE)

#define FW_HANDOFF_SIZE			0

#define BL31_LIMIT			(BL_RAM_BASE + BL_RAM_SIZE)
#define BL31_BASE			(BL31_LIMIT - 0x70000)
#define BL31_PROGBITS_LIMIT		BL31_LIMIT

#define BL32_MEM_BASE			BL_RAM_BASE
#define BL32_MEM_SIZE			BL_RAM_SIZE
#define BL32_BASE			BL_RAM_BASE
#define BL32_LIMIT			BL31_BASE

#define NS_IMAGE_OFFSET			(NS_DRAM0_BASE + 0x00080000)
#define NS_IMAGE_MAX_SIZE		(NS_DRAM0_SIZE - 0x00080000)
#define ARM_PRELOADED_DTB_BASE		(NS_DRAM0_BASE + 0x3f000000)

#define PLAT_PHY_ADDR_SPACE_SIZE	(1ULL << 32)
#define PLAT_VIRT_ADDR_SPACE_SIZE	(1ULL << 32)
#define MAX_MMAP_REGIONS		10
#define MAX_XLAT_TABLES			6
#define MAX_IO_DEVICES			1
#define MAX_IO_HANDLES			1

#define UART0_BASE			0x09000000
#define UART0_CLK_IN_HZ			24000000

#define JXL_CPU_PWRCTL_BASE		0x0a010000

#define PLAT_QEMU_BOOT_UART_BASE	UART0_BASE
#define PLAT_QEMU_BOOT_UART_CLK_IN_HZ	UART0_CLK_IN_HZ
#define PLAT_QEMU_CRASH_UART_BASE	UART0_BASE
#define PLAT_QEMU_CRASH_UART_CLK_IN_HZ	UART0_CLK_IN_HZ
#define PLAT_QEMU_CONSOLE_BAUDRATE	115200

#define QEMU_FLASH0_BASE		0x04000000
#define QEMU_FLASH0_SIZE		0x01000000
#define QEMU_FLASH1_BASE		0x04000000
#define QEMU_FLASH1_SIZE		0x01000000

#define DEVICE0_BASE			0x08000000
#define DEVICE0_SIZE			0x03000000

#define GICD_BASE			0x08000000
#define GICC_BASE			0x08010000
#define GICR_BASE			0x080a0000

#define QEMU_IRQ_SEC_SGI_0		8
#define QEMU_IRQ_SEC_SGI_1		9
#define QEMU_IRQ_SEC_SGI_2		10
#define QEMU_IRQ_SEC_SGI_3		11
#define QEMU_IRQ_SEC_SGI_4		12
#define QEMU_IRQ_SEC_SGI_5		13
#define QEMU_IRQ_SEC_SGI_6		14
#define QEMU_IRQ_SEC_SGI_7		15

#define PLATFORM_G1S_PROPS(grp)						\
	INTR_PROP_DESC(QEMU_IRQ_SEC_SGI_0, GIC_HIGHEST_SEC_PRIORITY,	\
		       grp, GIC_INTR_CFG_EDGE),				\
	INTR_PROP_DESC(QEMU_IRQ_SEC_SGI_1, GIC_HIGHEST_SEC_PRIORITY,	\
		       grp, GIC_INTR_CFG_EDGE),				\
	INTR_PROP_DESC(QEMU_IRQ_SEC_SGI_2, GIC_HIGHEST_SEC_PRIORITY,	\
		       grp, GIC_INTR_CFG_EDGE),				\
	INTR_PROP_DESC(QEMU_IRQ_SEC_SGI_3, GIC_HIGHEST_SEC_PRIORITY,	\
		       grp, GIC_INTR_CFG_EDGE),				\
	INTR_PROP_DESC(QEMU_IRQ_SEC_SGI_4, GIC_HIGHEST_SEC_PRIORITY,	\
		       grp, GIC_INTR_CFG_EDGE),				\
	INTR_PROP_DESC(QEMU_IRQ_SEC_SGI_5, GIC_HIGHEST_SEC_PRIORITY,	\
		       grp, GIC_INTR_CFG_EDGE),				\
	INTR_PROP_DESC(QEMU_IRQ_SEC_SGI_6, GIC_HIGHEST_SEC_PRIORITY,	\
		       grp, GIC_INTR_CFG_EDGE),				\
	INTR_PROP_DESC(QEMU_IRQ_SEC_SGI_7, GIC_HIGHEST_SEC_PRIORITY,	\
		       grp, GIC_INTR_CFG_EDGE)

#define PLATFORM_G0_PROPS(grp)						\
	INTR_PROP_DESC(QEMU_IRQ_SEC_SGI_0, GIC_HIGHEST_SEC_PRIORITY,	\
		       grp, GIC_INTR_CFG_EDGE)

#define PLAT_SDEI_NORMAL_PRI		0x70
#define PLAT_SDEI_CRITICAL_PRI		0x10
#define PLAT_SDEI_SGI_PRIVATE		QEMU_IRQ_SEC_SGI_0

#endif /* PLATFORM_DEF_H */
